#!/bin/sh

# 有待完善
# andy chen (bootoo@sina.cn)
#
#

#安装sublime text 2
install_sublime(){
echo "install begin..."
	sudo add-apt-repository ppa:webupd8team/sublime-text-2
	sudo apt-get update
	sudo apt-get install sublime-text
	#配置sublime text

echo "install success!"
}

#安装 chrome
install_chrome(){
	wget -c -O ./Downloads/Software/google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_i386.deb
	cd ./Downloads/Software
	sudo apt-get -f install
	sudo dpkg -i google-chrome.deb
}

#安装 firefox
install_firefox(){
	cd ~
	sudo apt-get install firefox
}

#安装 goagent 和 配置


#安装 重置linux文件名
reconfig_linux(){
	cd ~
	mv ./下载 Downloads
	mv ./公共的 Public
	mv ./音乐 Musics
	mv ./视频 Videos
	mv ./图片 Photos
	mv ./文档 Documents
	mv ./模板 Others

	sudo apt-get updat

	# 安装纠错
	sudo apt-get -f install

	# 安装vim	
	sudo apt-get install vim
	
	# 安装yum	
	sudo apt-get install yum

	# 安装alien
	sudo apt-get install alien

	# 安装unrar
	sudo apt-get install unrar

	echo "uninstall midori..."
	sudo apt-get autoremove midori-granite
} 

#安装 goagent 和 配置


#reconfig_linux
#install_chrome
#install_firefox
#install_sublime

